services:
  jobinow-db:
    image: 'postgres:latest'
    container_name: jobinow-db
    environment:
      - POSTGRES_DB=jobinow
      - POSTGRES_PASSWORD=Youcode@2023
      - POSTGRES_USER=postgres
      - PGDATA=/data/postgres
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres-db
        target: /var/lib/postgresql/data
    networks:
      - jobinow

  jobinow-cache:
    image: 'redis:latest'
    container_name: jobinow-cache
    hostname: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "6379:6379"
    restart: always
    networks:
      - jobinow

  jobinow-api:
    container_name: jobinow-api
    build:
      context: .
      dockerfile: Dockerfile
    image: jobinow-api
    ports:
      - "8085:8084"
    depends_on:
      jobinow-db:
        condition: service_healthy
      jobinow-cache:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - jobinow

networks:
  jobinow:
    attachable: true
    name: jobinow
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB7::/112

volumes:
  postgres-db:
    driver: local