services:
  database:
    image: 'postgres:latest'
    container_name: database
    environment:
      - POSTGRES_DB=Jobinow
      - POSTGRES_PASSWORD=Youcode@2023
      - POSTGRES_USER=postgres
      - PGDATA=/data/postgres
    restart: always
    ports:
      - "5433"
    volumes:
      - type: volume
        source: postgres-db
        target: /var/lib/postgresql/data
    networks:
      - jobinow

  api:
    container_name: jobinow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8084"
    depends_on:
      - database
    restart: no
    networks:
      - jobinow

networks:
  jobinow:
    attachable: true
    name: jobinow
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB8::/112

volumes:
  postgres-db:
    driver: local