services:
  jobinow-db:
    image: 'postgres:latest'
    container_name: jobinow-db
    environment:
      - POSTGRES_DB=Jobinow
      - POSTGRES_PASSWORD=Youcode@2023
      - POSTGRES_USER=postgres
      - PGDATA=/data/postgres
    restart: always
    ports:
      - "5432"
    volumes:
      - type: volume
        source: postgres-db
        target: /var/lib/postgresql/data
    networks:
      - jobinow

  api:
    container_name: jobinow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8083"
    depends_on:
      - jobinow-db
    restart: no
    networks:
      - jobinow

networks:
  jobinow:
    attachable: true
    name: jobinow
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB7::/112

volumes:
  postgres-db:
    driver: local