server:
  port: 8084

logging:
  level:
    org.springframework.beans.factory: ERROR
    org.springframework.security: trace

spring:
  application:
    name: jobinow
    admin:
      enabled: true
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true
  data:
    redis:
      database: 0
      repositories:
        enabled: false
      host: jobinow-cache
      port: 6379
  docker:
    compose:
      enabled: true
      file: compose.yaml
  datasource:
    url: jdbc:postgresql://
    username:
    password:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    open-in-view: false
  quartz:
    jdbc:
      initialize-schema: always
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
          scheduler:
            instanceId: AUTO
          threadPool:
            threadCount: 5
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: https://www.googleapis.com/
          clientId:
          clientSecret:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

application:
  stripe:
    secret-key:
  security:
    jwt:
      secret-key:
      expiration:
      refresh-token:
        expiration: