server:
  port: 8084

logging:
  level:
    org.springframework.beans.factory: ERROR

spring:
  data:
    redis:
      database: 0
      host: jobinow-cache
      port: 6379
  docker:
    compose:
      enabled: true
      file: compose.yaml
  datasource:
    url: jdbc:postgresql://jobinow-db:5432/jobinow
    username: postgres
    password: Youcode@2023
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  quartz:
    jdbc:
      initialize-schema: always
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
          scheduler:
            instanceId: AUTO
          threadPool:
            threadCount: 5
  mail:
    host: smtp.gmail.com
    port: 587
    username: fadwacherqui2@gmail.com
    password: cmup wxrx rusq tapz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

application:
  stripe:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000